Jump to page number in pdf added
Yashshukla11/ExamTime_android pull request #42
Opened 2024-05-12 20:11 UTC by ShashankDeepak

## Context
This PR is intended to resolve the issue #24 

## Description 
With this PR a feature would be introduced where the user can directly jump to page number while reading the document

## Codebase changes
The changes are mainly occurred in lib\screens\landing_screen\popupdetail.dart file.

## Video of new feature

https://github.com/Yashshukla11/ExamTime_android/assets/92669664/72e84f5a-dae2-4229-9547-dd48c23b2659

2024-05-12 20:15 UTC, ShashankDeepak commented
@Yashshukla11 Can you please check why the greetings check is failing? It is probably not occurring from the code repository but from GitHub itself.

2024-05-12 20:42 UTC, Yashshukla11 requested changes
first, the scrolling should be vertically and the make the search place some where below appbar or in appbar.

secondly I have removed the description bar and put it into appbar so just update the fork and re-clone the project and update changes.

<br>
<img width="299" alt="Screenshot 2024-05-13 at 2 01 44 AM" src="https://github.com/Yashshukla11/ExamTime_android/assets/112846526/86c9c56c-add2-46bd-be31-40c12349f604">

2024-05-13 07:02 UTC, ShashankDeepak commented
@Yashshukla11 I have updated the UI please have a look

## Video
https://github.com/Yashshukla11/ExamTime_android/assets/92669664/cfc0b23b-3c9b-4b9e-8b7a-7148b72d45e0

2024-05-13 08:32 UTC, Yashshukla11 approved these changes

2024-05-13 08:33 UTC, merged